#  redis 单机配置
spring:
  redis:
    host:
    port: 6379
    lettuce:
      pool:
        max-wait: 100000
        max-idle: 10
        max-active: 100
    timeout: 5000


#  集群设置
#spring:
#  redis:
#    database: 0
#    # 集群设置 begin
#    cluster:
#      nodes:
#        - 10.217.17.70:7000
#        - 10.217.17.74:7000
#        - 10.217.17.75:7000
#      max-redirects: 3 # 获取失败 最大重定向次数
#    #集群设置 end
#    #单节点 begin
#    #    host: 10.217.17.74
#    #    port: 7000
#    #单节点 end
#    lettuce:
#      pool:
#        max-wait: 100000
#        max-idle: 10
#        max-active: 100
#    timeout: 5000